# Generated by Django 5.2.4 on 2025-09-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_feedback_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
