# Generated by Django 5.2.4 on 2025-09-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipes_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
